### ISSUE TITLE
ssl报错

### ISSUE THREAD

**Issue by pollysu** [shidenggui/easytrader#12]
>>> user.prepare('ht.json')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "easytrader/webtrader.py", line 55, in prepare
    self.autologin()
  File "easytrader/webtrader.py", line 59, in autologin
    is_login_ok = self.login()
  File "easytrader/httrader.py", line 74, in login
    self.__go_login_page()
  File "easytrader/httrader.py", line 97, in __go_login_page
    self.s.get(self.config['logout_api'])
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)

**Comment by shidenggui** [comment]
使用 feature_ht_ssl3 这个分支的代码试下行不行

**Comment by pollysu** [comment]
已经解决了，应该是缓存的证书过期了的问题，换了新的解决了
