### ISSUE TITLE
广发的买入操作有问题

### ISSUE THREAD

**Issue by indigo200** [shidenggui/easytrader#142]
>>> user.buy('162510', price=1.097, amount=200)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/site-packages/easytrader/gftrader.py", line 174, in buy
    return self.__trade(stock_code, price, other=params)
  File "/usr/local/lib/python3.5/site-packages/easytrader/gftrader.py", line 385, in __trade
    need_info = self.__get_trade_need_info(stock_code)
  File "/usr/local/lib/python3.5/site-packages/easytrader/gftrader.py", line 152, in __get_trade_need_info
    else self.holdername[SZ]['exchange_type']
IndexError: list index out of range

**Comment by shidenggui** [comment]
我没有广发的账号，可能要自己调试下，你试试加上用 ‘sh162510' 看看行不行

**Comment by indigo200** [comment]
可以结束这个话题了。原来是自己没有开沪市。。
