### ISSUE TITLE
easytrader 下单时报错。

### ISSUE THREAD

**Issue by syauwjl** [shidenggui/easytrader#145]
您好，我在使用easytrader的时候下单报错。

我的代码是：
>>> quotation = easyquotation.use('sina')
>>> dict_quotation= quotation.stocks('600051')
>>> wuser = easytrader.use('xq')
>>> wuser.prepare(r'G:\\anaconda\\easyquant\\xq.json')
2016-10-24 10:48:05,838 [DEBUG] xqtrader.py 54: login status: SUCCESS
>>> wuser.adjust_weight('000001', 10)
最后一步用user.buy 函数也报错。

报错：
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "G:\anaconda\lib\site-packages\easytrader\xqtrader.py", line 447, in buy
    return self.__trade(stock_code, price, amount, volume, 'buy')
  File "G:\anaconda\lib\site-packages\easytrader\xqtrader.py", line 338, in __trade
    stock = self.__search_stock_info(stock_code)
  File "G:\anaconda\lib\site-packages\easytrader\xqtrader.py", line 96, in __search_stock_info
    'market': self.account_config['portfolio_market'],
KeyError: 'portfolio_market'

能否请大神指教一下，谢谢了。

**Comment by shidenggui** [comment]
xq.json 没有对应的字段，格式看这里 https://github.com/shidenggui/easytrader/blob/master/xq.json
