### ISSUE TITLE
跟踪雪球组合时报错

### ISSUE THREAD

**Issue by pollysu** [shidenggui/easytrader#161]
>>> xq_follower.follow(xq_user, 'ZH894050', total_assets=1000)
2016-11-30 10:36:12,956 [INFO] xq_follower.py 74: 开始跟踪策略: testtest
>>> {u'error_uri': u'/cubes/rebalancing/history.json', u'error_code': u'10022', u'error_description': u''}
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/site-packages/easytrader/follower.py", line 145, in track_strategy_worker
    transactions = self.query_strategy_transaction(strategy, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/easytrader/follower.py", line 257, in query_strategy_transaction
    transactions = self.extract_transactions(history)
  File "/usr/local/lib/python2.7/site-packages/easytrader/xq_follower.py", line 101, in extract_transactions
    if history['count'] <= 0:
KeyError: u'count'

**Comment by shidenggui** [comment]
看了下，这个组合没有历史记录，应该是雪球那边的有些组合有问题
