### ISSUE TITLE
银河客户端——启动客户端失败，无法检测到登陆窗口

### ISSUE THREAD

**Issue by easunlu** [shidenggui/easytrader#182]
@shidenggui
能够在界面上打开银河双子星客户端，但没有进一步操作，报错详情为：
Traceback (most recent call last):
  File "C:/Users/easun.lu/examples/god_wind/center_command.py", line 5, in <module>
    user.prepare(user='20**0**0**4**', password='******')
  File "C:\Program  @Files\Anaconda3\envs\oldpython\lib\site-packages\easytrader\yh_clienttrader.py", line 41, in prepare
    self.login(user, password, exe_path)
  File "C:\Program Files\Anaconda3\envs\oldpython\lib\site-packages\easytrader\yh_clienttrader.py", line 58, in login
    raise Exception('启动客户端失败，无法检测到登陆窗口')
Exception: 启动客户端失败，无法检测到登陆窗口

**Comment by easunlu** [comment]
断点调试了下，错误大概是从这里开始的：
    def _get_handles(self):
        trade_main_hwnd = win32gui.FindWindow(0, self.Title)  # 交易窗口  Variables: trade_main_hwnd: 0

**Comment by shidenggui** [comment]
推荐直接用web版本，银河的客户端版本我找时间看下

**Comment by easunlu** [comment]
感谢！
