### ISSUE TITLE
使用银河账户 命令行买入沪市股票时返回错误

### ISSUE THREAD

**Issue by pengchx** [shidenggui/easytrader#190]
D:\easytrader>python cli.py --do buy 600010 0.450 100
Traceback (most recent call last):
  File "cli.py", line 41, in <module>
    main()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python36\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "cli.py", line 32, in main
    result = getattr(user, do)(*params)
  File "D:\easytrader\easytrader\yhtrader.py", line 299, in buy
    return self.__trade(stock_code, price, entrust_prop=entrust_prop, other=params)
  File "D:\easytrader\easytrader\yhtrader.py", line 408, in __trade
    need_info = self.__get_trade_need_info(stock_code)
  File "D:\easytrader\easytrader\yhtrader.py", line 429, in __get_trade_need_info
    exchange_type=exchange_type,stock_account=self.exchange_stock_account[exchange_type]
KeyError: '1'

**Comment by shidenggui** [comment]
你没有开通沪市股东账号吧。现在一人三户，超过的只能开深市的，需要注销原来的
