### ISSUE TITLE
最近银河的验证码老报错，自动识别银河验证码失败

### ISSUE THREAD

**Issue by tianxiawuzhe** [shidenggui/easytrader#224]
最近1个月老是报验证码错误，错误信息如下：
2017-08-02 17:16:02,472 [ERROR] helpers.py 182: 自动识别银河验证码失败: request http://123.56.157.162:5000/yh error, 请手动输入验证码
Traceback (most recent call last):
  File "/code/app/trader.py", line 80, in __login
    use.prepare(os.path.dirname(__file__) + '/config/yh.json')
  File "/usr/local/lib/python2.7/site-packages/easytrader/webtrader.py", line 73, in prepare
    self.autologin()
  File "/usr/local/lib/python2.7/site-packages/easytrader/webtrader.py", line 84, in autologin
    if self.login():
  File "/usr/local/lib/python2.7/site-packages/easytrader/yhtrader.py", line 55, in login
    verify_code = self.handle_recognize_code()
  File "/usr/local/lib/python2.7/site-packages/easytrader/yhtrader.py", line 86, in handle_recognize_code
    verify_code = helpers.recognize_verify_code(image_path, 'yh')
  File "/usr/local/lib/python2.7/site-packages/easytrader/helpers.py", line 84, in recognize_verify_code
    return detect_yh_result(image_path)
  File "/usr/local/lib/python2.7/site-packages/easytrader/helpers.py", line 183, in detect_yh_result
    return input_verify_code_manual(image_path)
  File "/usr/local/lib/python2.7/site-packages/easytrader/helpers.py", line 108, in input_verify_code_manual
    image = Image.open(image_path)
  File "/usr/local/lib/python2.7/site-packages/PIL/Image.py", line 2286, in open
    % (filename if filename else fp))
IOError: cannot identify image file u'/root/vcode'
我刚才更新了下最新程序，也还是同样错误，请问有遇到过么？如何解决？多谢多谢~~~

**Comment by shenxingbei** [comment]
银河web已经关停一个月了。。。

**Comment by shidenggui** [comment]
银河web已经关闭了
