### ISSUE TITLE
2017-9-7 广发登录报错

### ISSUE THREAD

**Issue by matrixleon18** [shidenggui/easytrader#229]
Traceback (most recent call last):
  File "test.py", line 100, in <module>
    m = easyquant.MainEngine(broker_data, account_data, quotation_engines=[quotation_engine], log_handler=log_data)
  File "D:\easyquant\easyquant\main_engine.py", line 44, in __init__
    self.user.prepare(need_data)
  File "C:\Python36\lib\site-packages\easytrader\webtrader.py", line 73, in prepare
    self.autologin()
  File "C:\Python36\lib\site-packages\easytrader\webtrader.py", line 84, in autologin
    if self.login():
  File "C:\Python36\lib\site-packages\easytrader\gftrader.py", line 78, in login
    login_status, result = self.post_login_data(verify_code)
  File "C:\Python36\lib\site-packages\easytrader\gftrader.py", line 96, in post_login_data
    self.__set_trade_need_info()
  File "C:\Python36\lib\site-packages\easytrader\gftrader.py", line 155, in __set_trade_need_info
    jsholder = eval(jsholder[0])
IndexError: list index out of range

**Comment by fndjjx** [comment]
我也报这个错了 提示9月15号之后就不能用web页面了

**Comment by shidenggui** [comment]
广发15日关闭web

**Comment by fndjjx** [comment]
现在比较推荐的是用哪个券商

**Comment by shidenggui** [comment]
使用客户端。目前正在完善中，web不准备再开发了。耗时耗力而且容易关闭

**Comment by matrixleon18** [comment]
在开发GF的客户端模拟器？还是按键精灵那种？
