### ISSUE TITLE
刚刚启动客户端时取position报错

### ISSUE THREAD

**Issue by marzwu** [shidenggui/easytrader#232]
关键信息：
pywinauto.findwindows.ElementNotFoundError: {'control_id': 1047, 'class_name': 'CVirtualGridCtrl', 'top_level_only': False, 'parent': <win32_element_info.HwndElementInfo - '', Afx:400000:843:0:5:0, 596262>, 'backend': 'win32'}

详细堆栈：
`D:\Anaconda3\lib\site-packages\pywinauto\application.py:1032: UserWarning: 32-bit application should be automated using 32-bit Python (you use 64-bit Python)
  UserWarning)
D:\Anaconda3\lib\site-packages\pywinauto\application.py:1032: UserWarning: 32-bit application should be automated using 32-bit Python (you use 64-bit Python)
  UserWarning)
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\pywinauto\application.py", line 245, in __resolve_control
    criteria)
  File "D:\Anaconda3\lib\site-packages\pywinauto\timings.py", line 447, in wait_until_passes
    raise err
pywinauto.timings.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Program Files\JetBrains\PyCharm 2017.2\helpers\pydev\pydevd.py", line 1599, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "D:\Program Files\JetBrains\PyCharm 2017.2\helpers\pydev\pydevd.py", line 1026, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Program Files\JetBrains\PyCharm 2017.2\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:/github/analyze/etf_runner.py", line 151, in <module>
    sell_and_buy()
  File "D:/github/analyze/etf_runner.py", line 70, in sell_and_buy
    position = user.position
  File "D:\github\easytrader\easytrader\yh_clienttrader.py", line 107, in position
    return self._get_grid_data(self._config.COMMON_GRID_CONTROL_ID)
  File "D:\github\easytrader\easytrader\yh_clienttrader.py", line 238, in _get_grid_data
    grid.type_keys('^A^C')
  File "D:\Anaconda3\lib\site-packages\pywinauto\application.py", line 351, in __getattribute__
    ctrls = self.__resolve_control(self.criteria)
  File "D:\Anaconda3\lib\site-packages\pywinauto\application.py", line 248, in __resolve_control
    raise e.original_exception
  File "D:\Anaconda3\lib\site-packages\pywinauto\timings.py", line 425, in wait_until_passes
    func_val = func(*args)
  File "D:\Anaconda3\lib\site-packages\pywinauto\application.py", line 209, in __get_ctrl
    ctrl = self.backend.generic_wrapper_class(findwindows.find_element(**ctrl_criteria))
  File "D:\Anaconda3\lib\site-packages\pywinauto\findwindows.py", line 87, in find_element
    raise ElementNotFoundError(kwargs)
pywinauto.findwindows.ElementNotFoundError: {'control_id': 1047, 'class_name': 'CVirtualGridCtrl', 'top_level_only': False, 'parent': <win32_element_info.HwndElementInfo - '', Afx:400000:843:0:5:0, 596262>, 'backend': 'win32'}`

**Comment by shidenggui** [comment]
版本号说下

**Comment by marzwu** [comment]
昨晚在qq也说了一下，你已经把它修复了。issue怎么关闭来着？
