### ISSUE TITLE
使用华泰客户端是否只支持windows系统？

### ISSUE THREAD

**Issue by paulhebo** [shidenggui/easytrader#238]
使用linux登录报错：
Traceback (most recent call last):
  File "testBuy1.py", line 4, in <module>
    user = easytrader.use('ht_client')
  File "/usr/local/python3.6/lib/python3.6/site-packages/easytrader/api.py", line 35, in use
    from .ht_clienttrader import HTClientTrader
  File "/usr/local/python3.6/lib/python3.6/site-packages/easytrader/ht_clienttrader.py", line 13, in <module>
    import pywinauto.clipboard
  File "/usr/local/python3.6/lib/python3.6/site-packages/pywinauto/clipboard.py", line 34, in <module>
    import win32clipboard
ModuleNotFoundError: No module named 'win32clipboard'

**Comment by shidenggui** [comment]
是的
