### ISSUE TITLE
银河客户端验证码问题

### ISSUE THREAD

**Issue by geniuszhe** [shidenggui/easytrader#250]
银河客户端是不是增加了验证码，现在不能正常执行呢，我也是第一次接入，之前是用web接口的

**Comment by geniuszhe** [comment]
看了下有处理验证码的代码，但是过不去呢

**Comment by shidenggui** [comment]
你具体信息提供下

**Comment by luyh** [comment]
参考 #249 我用了银河证券双子星单独委托版的客户端。 验证码大概有一半概率会错误
>  File "C:\WinPython-32bit-3.5.4.0Qt5\python-3.5.4\lib\site-packages\pywinauto\findbestmatch.py", line 533, in find_best_control_matches
    raise MatchError(items = name_control_map.keys(), tofind = search_text)
pywinauto.findbestmatch.MatchError: Could not find 'Edit3' in 'dict_keys(['验证码错误，请重新输入！', '提示', '验证码错误，请重新输入！Static', 'Button', 'Static0', '提示Static', 'Static1', '确定Button', 'Static', 'Static2', '确定'])'

**Comment by geniuszhe** [comment]
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\pywinauto\application.py", line 936, in co
nnect
    ProcessNotFoundError, kwargs['path'],
  File "C:\Python36\lib\site-packages\pywinauto\timings.py", line 447, in wait_u
ntil_passes
    raise err
pywinauto.timings.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\easytrader\yh_clienttrader.py", line 37, i
n login
    self._app = pywinauto.Application().connect(path=self._run_exe_path(exe_path
), timeout=1)
  File "C:\Python36\lib\site-packages\pywinauto\application.py", line 939, in co
nnect
    raise ProcessNotFoundError('Process "{}" not found!'.format(kwargs['path']))

pywinauto.application.ProcessNotFoundError: Process "C:\中国银河证券双子星3.2\xi
adan.exe" not found!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "min_jq.py", line 4, in <module>
    user.prepare('C:\\jq\\yh.json')
  File "C:\Python36\lib\site-packages\easytrader\clienttrader.py", line 30, in p
repare
    self.login(user, password, exe_path or self._config.DEFAULT_EXE_PATH, comm_p
assword, **kwargs)
  File "C:\Python36\lib\site-packages\easytrader\yh_clienttrader.py", line 54, i
n login
    self._handle_verify_code()
  File "C:\Python36\lib\site-packages\easytrader\yh_clienttrader.py", line 87, i
n _handle_verify_code
    control.capture_as_image().save(file_path, 'jpeg')
AttributeError: 'NoneType' object has no attribute 'save'

**Comment by geniuszhe** [comment]
找到问题了由于pywinauto依赖pillow ，我安装了pillow可以截图，正常都登录了
