### ISSUE TITLE
linux端需要装什么客户端吗？有提示错误

### ISSUE THREAD

**Issue by ywdyy** [shidenggui/easytrader#251]
## env

OS: linux centos6.5
PYTHON_VERSION: 3.6.3
EASYTRADER_VERSION: 0.12.3

## problem
import easytrader
user = easytrader.use('ht_client')
出现以下异常提示：
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/easytrader/api.py", line 35, in use
    from .ht_clienttrader import HTClientTrader
  File "/usr/local/lib/python3.6/site-packages/easytrader/ht_clienttrader.py", line 13, in <module>
    import pywinauto.clipboard
  File "/usr/local/lib/python3.6/site-packages/pywinauto/clipboard.py", line 34, in <module>
    import win32clipboard
ModuleNotFoundError: No module named 'win32clipboard'

**Comment by ywdyy** [comment]
这个只能在window环境运行吗？然后装上银河／华泰的客户端？

**Comment by ywdyy** [comment]
雪球只有网页端和手机app端嘛，那雪球就不用装客户端了是吧，需要打开雪球这个网址吗？

**Comment by shidenggui** [comment]
雪球只支持模拟组合。其他的需要win客户端

**Comment by ywdyy** [comment]
嗯，我试试，感谢感谢！

**Comment by Xiaohong-Deng** [comment]
建议修改一下README，现在linux下不能做实盘操作了，对吗？RADME还是 Linux / Windows, 使人困惑

**Comment by shidenggui** [comment]
@Xiaohong-Deng 改了，目前 Linux 仅支持雪球模拟
