### ISSUE TITLE
control.capture_as_image().save(file_path, 'jpeg') AttributeError: 'NoneType' object has no attribute 'save'

### ISSUE THREAD

**Issue by Zhangjiahong001** [shidenggui/easytrader#253]
## env

OS: win10
PYTHON_VERSION: 3.5
EASYTRADER_VERSION: 0.12.3

## problem
 user.prepare(user='xxxxx',password='xxxxx')
C:\Users\82193\Python35\lib\site-packages\pywinauto\application.py:1032: UserWarning: 32-bit application should be automated using 32-bit Python (you use 64-bit Python)
  UserWarning)
PIL does not seem to be installed. PIL is required for capture_as_image
Traceback (most recent call last):
  File "C:\Users\82193\Python35\lib\site-packages\pywinauto\timings.py", line 425, in wait_until_passes
    func_val = func(*args)
  File "C:\Users\82193\Python35\lib\site-packages\pywinauto\application.py", line 1381, in process_from_module
    raise ProcessNotFoundError(message)
pywinauto.application.ProcessNotFoundError: Could not find any accessible process with a module of 'C:\中国银河证券双子 星3.2\xiadan.exe'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\82193\Python35\lib\site-packages\pywinauto\application.py", line 936, in connect
    ProcessNotFoundError, kwargs['path'],
  File "C:\Users\82193\Python35\lib\site-packages\pywinauto\timings.py", line 447, in wait_until_passes
    raise err
pywinauto.timings.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\82193\Python35\lib\site-packages\easytrader\yh_clienttrader.py", line 37, in login
    self._app = pywinauto.Application().connect(path=self._run_exe_path(exe_path), timeout=1)
  File "C:\Users\82193\Python35\lib\site-packages\pywinauto\application.py", line 939, in connect
    raise ProcessNotFoundError('Process "{}" not found!'.format(kwargs['path']))
pywinauto.application.ProcessNotFoundError: Process "C:\中国银河证券双子星3.2\xiadan.exe" not found!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\82193\Python35\lib\site-packages\easytrader\clienttrader.py", line 30, in prepare
    self.login(user, password, exe_path or self._config.DEFAULT_EXE_PATH, comm_password, **kwargs)
  File "C:\Users\82193\Python35\lib\site-packages\easytrader\yh_clienttrader.py", line 54, in login
    self._handle_verify_code()
  File "C:\Users\82193\Python35\lib\site-packages\easytrader\yh_clienttrader.py", line 88, in _handle_verify_code
    control.capture_as_image().save(file_path, 'jpeg')
AttributeError: 'NoneType' object has no attribute 'save'

**Comment by shidenggui** [comment]
注意报错里面有这句话  “PIL does not seem to be installed. PIL is required for capture_as_image”， 需要安装 PIL，安装命令 `pip install pillow`
