### ISSUE TITLE
华泰客户端买卖报错

### ISSUE THREAD

**Issue by luyulong3538** [shidenggui/easytrader#257]
## env
阿里云win sever 2008 企业版
python 3.5
华泰证券客户端网上交易系统（专业版Ⅱ）V5.50
（其他版本也报相同错误）

## 调用代码
user=easytrader.use('ht_client')
user.prepare(user='xxxx',password='xxx',comm_password='xxx')
user.sell('162411',price=0.650,amount=100)

## 报错
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pywinauto\application.py", line 245, in __resolve_control
    criteria)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pywinauto\timings.py", line 447, in wait_until_passes
    raise err
pywinauto.timings.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/个人文件/xxx", line 18, in <module>
    user.sell('162411',price=0.650,amount=100)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\site-packages\easytrader\clienttrader.py", line 129, in sell
    return self.trade(security, price, amount)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\site-packages\easytrader\clienttrader.py", line 257, in trade
    self._submit_trade()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\site-packages\easytrader\clienttrader.py", line 297, in _submit_trade
    class_name='Button'
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pywinauto\application.py", line 351, in __getattribute__
    ctrls = self.__resolve_control(self.criteria)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pywinauto\application.py", line 248, in __resolve_control
    raise e.original_exception
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pywinauto\timings.py", line 425, in wait_until_passes
    func_val = func(*args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pywinauto\application.py", line 209, in __get_ctrl
    ctrl = self.backend.generic_wrapper_class(findwindows.find_element(**ctrl_criteria))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pywinauto\findwindows.py", line 87, in find_element
    raise ElementNotFoundError(kwargs)
pywinauto.findwindows.ElementNotFoundError: {'backend': 'win32', 'parent': <win32_element_info.HwndElementInfo - '', Afx:400000:843:0:5:0, 526298>, 'class_name': 'Button', 'top_level_only': False, 'control_id': 1006}

似乎并未点击卖出按钮，客户端买卖设置已按要求设置为空。

**Comment by shidenggui** [comment]
没有 windows 云服务器。你在本地能正常使用吗？

**Comment by luyulong3538** [comment]
我本地环境没有配置，回头有时间弄了试下。但云服务器我测试过银河证券账户，使用正常。只是华泰不正常，不知道是不是因为华泰买卖的时候会跳出一个框有影响。
![image](https://user-images.githubusercontent.com/15365365/35100241-094f1bce-fc96-11e7-83b4-a948d5d6c56a.png)

**Comment by shidenggui** [comment]
我在本地是正常使用的，应该不是这个问题

**Comment by luyulong3538** [comment]
哦哦。多谢。我再查查吧。

**Comment by shidenggui** [comment]
今天我改了下代码然后又跑了下测试，发现我本地也不行了，我记得以前跑测试都正常的

**Comment by luyulong3538** [comment]
感谢。

**Comment by izhangmh** [comment]
我一台老电脑上是可以的，换新电脑后也偶尔错误，请问这个问题怎么解决的？
