### ISSUE TITLE
pip install git+https安装后无法正常启动server中的prepare

### ISSUE THREAD

**Issue by byron0416** [shidenggui/easytrader#264]
## env
 win10
## problem
无法通过server方式远程启动银河证券程序
Traceback (most recent call last):
  File "C:\Users\byron\Documents\private\test\git\easytrader\easytrader\server.py", line 17, in wrapper
    return f(*args, **kwargs)
  File "C:\Users\byron\Documents\private\test\git\easytrader\easytrader\server.py", line 32, in post_prepare
    user.prepare(**json_data)
  File "C:\Users\byron\Documents\private\test\git\easytrader\easytrader\clienttrader.py", line 108, in prepare
    self.login(user, password, exe_path or self._config.DEFAULT_EXE_PATH, comm_password, **kwargs)
  File "C:\Users\byron\Documents\private\test\git\easytrader\easytrader\yh_clienttrader.py", line 45, in login
    self._app.top_window().Edit3.type_keys(
  File "C:\Users\byron\AppData\Local\conda\conda\envs\python35\lib\site-packages\pywinauto\application.py", line 1051, in top_window
    raise RuntimeError("No windows for that process could be found")
## how to repeat
通过pip install git+http方式安装，或git install --upgrade easytrader后，均无法通过server.py正式启动银河双子星客户端。

**Comment by byron0416** [comment]
pywinauto 0.6.0 -> 0.6.4
comtypes 1.1.3 -> 1.14
版降回后也不work

**Comment by byron0416** [comment]
- yh_clienttrader.py:52 self._app.top_window().wait_not('exists', 10)
+ yh_clienttrader.py:52 self._app.top_window().wait_not('exists visible', 10)
可以正常work，有什么副作用目前不知道。

**Comment by byron0416** [comment]
diff --git a/easytrader/yh_clienttrader.py b/easytrader/yh_clienttrader.py
index 7030f87..ad63eff 100644
--- a/easytrader/yh_clienttrader.py
+++ b/easytrader/yh_clienttrader.py
@@ -51,8 +51,10 @@ class YHClientTrader(ClientTrader):
                 try:
                     self._app.top_window().wait_not('exists', 10)
                     break
-                except:
-                    pass
+               except TimeoutError as e:
+                   pass
+               except RuntimeError as e:
+                   break
