### ISSUE TITLE
华泰客户端 windows server 2012R2,跑程序出错，ImportError: DLL load failed: 找不到指定的模块

### ISSUE THREAD

**Issue by Wangj** [shidenggui/easytrader#286]
## env

OS: win server 2012 R2
PYTHON_VERSION: 3.6.5
EASYTRADER_VERSION: 0.xx.xx，当前最新的版本
BROKER_TYPE: ht 

## problem
PS C:\Users\Administrator\Desktop> python .\trade.py
Traceback (most recent call last):
  File ".\trade.py", line 3, in <module>
    user = easytrader.use('ht_client')
  File "C:\Python36\lib\site-packages\easytrader\api.py", line 36, in use
    from .ht_clienttrader import HTClientTrader
  File "C:\Python36\lib\site-packages\easytrader\ht_clienttrader.py", line 6, in <module>
    from .clienttrader import ClientTrader
  File "C:\Python36\lib\site-packages\easytrader\clienttrader.py", line 11, in <module>
    import pandas as pd
  File "C:\Python36\lib\site-packages\pandas\__init__.py", line 42, in <module>
    from pandas.core.api import *
  File "C:\Python36\lib\site-packages\pandas\core\api.py", line 10, in <module>
    from pandas.core.groupby.groupby import Grouper
  File "C:\Python36\lib\site-packages\pandas\core\groupby\__init__.py", line 2, in <module>
    from pandas.core.groupby.groupby import (
  File "C:\Python36\lib\site-packages\pandas\core\groupby\groupby.py", line 49, in <module>
    from pandas.core.frame import DataFrame
  File "C:\Python36\lib\site-packages\pandas\core\frame.py", line 74, in <module>
    from pandas.core.series import Series
  File "C:\Python36\lib\site-packages\pandas\core\series.py", line 3978, in <module>
    Series._add_series_or_dataframe_operations()
  File "C:\Python36\lib\site-packages\pandas\core\generic.py", line 8891, in _add_series_or_dataframe_operations
    from pandas.core import window as rwindow
  File "C:\Python36\lib\site-packages\pandas\core\window.py", line 36, in <module>
    import pandas._libs.window as _window
ImportError: DLL load failed: 找不到指定的模块。
## how to repeat
import easytrader

user = easytrader.use('ht_client')
user.prepare(user='', password=' ', comm_password='')
xq_follower = easytrader.follower('xq')
xq_follower.login(cookies= '写入雪球cookies')
xq_follower.follow(user, 'ZH507999', total_assets=10000)

**Comment by Wangj** [comment]
重装并更换了系统，在Windows Server 2008 R2 企业版 SP1，重新安装跑了下，还是报以上的错误，券商的交易软件用户的是您提供的版本 [https://github.com/shidenggui/easytrader/issues/272](url)

**Comment by shidenggui** [comment]
看错误应该是 `pandas` 的错误，跟 `easytrader` 没关系

**Comment by Wangj** [comment]
@shidenggui 安装了3.5.4版本，还是报一样的错误（刚开始安装了3.5.0版本，pip安装pandas不成功，3.5.4装成功了）

**Comment by Wangj** [comment]
以上是云端系统上报的错，自己的笔记本是Windows 10，安装了python3.6.5，可以正常运行的

**Comment by jayqqaa12** [comment]
我也遇到了 解决了  uninstall pandas   然后安装0.22 版本的就可以了
