### ISSUE TITLE
华泰客户端，user.balance报错

### ISSUE THREAD

**Issue by cdxhcm1995** [shidenggui/easytrader#305]
## env

OS: win10 
PYTHON_VERSION: 3.6
EASYTRADER_VERSION: 0.17.0
BROKER_TYPE: ht

## problem
    user = easytrader.use('ht_client')
    user.prepare(user=user_id, password=password, comm_password=comm_password)
    user.connect(path)
    print ("User init successfully!")
    print ("Balance:")
    print (user.balance)
报错：

Traceback (most recent call last):
  File "C:\Users\Duoxiao Chang\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinauto\application.py", line 245, in __resolve_control
    criteria)
  File "C:\Users\Duoxiao Chang\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinauto\timings.py", line 449, in wait_until_passes
    raise err
pywinauto.timings.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\workspace_cdx\auto_trader\trader\trader.py", line 9, in init_trader
    print (user.balance)
  File "C:\Users\Duoxiao Chang\AppData\Local\Programs\Python\Python36\lib\site-packages\easytrader\ht_clienttrader.py", line 61, in balance
    return self._get_balance_from_statics()
  File "C:\Users\Duoxiao Chang\AppData\Local\Programs\Python\Python36\lib\site-packages\easytrader\ht_clienttrader.py", line 68, in _get_balance_from_statics
    control_id=control_id, class_name="Static"
  File "C:\Users\Duoxiao Chang\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinauto\application.py", line 351, in __getattribute__
    ctrls = self.__resolve_control(self.criteria)
  File "C:\Users\Duoxiao Chang\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinauto\application.py", line 248, in __resolve_control
    raise e.original_exception
  File "C:\Users\Duoxiao Chang\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinauto\timings.py", line 427, in wait_until_passes
    func_val = func(*args)
  File "C:\Users\Duoxiao Chang\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinauto\application.py", line 209, in __get_ctrl
    ctrl = self.backend.generic_wrapper_class(findwindows.find_element(**ctrl_criteria))
  File "C:\Users\Duoxiao Chang\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinauto\findwindows.py", line 87, in find_element
    raise ElementNotFoundError(kwargs)
pywinauto.findwindows.ElementNotFoundError: {'control_id': 1012, 'class_name': 'Static', 'top_level_only': False, 'parent': <win32_element_info.HwndElementInfo - '网上股票交易系统5.0', AfxFrameOrView42s, 1248952>, 'backend': 'win32'}

**Comment by shidenggui** [comment]
你交易软件打开了吗？

**Comment by cdxhcm1995** [comment]
打开，用的是你提供的交易软件
