### ISSUE TITLE
user.prepare登陆时 pywinauto.findwindows.ElementNotFoundError: 报错

### ISSUE THREAD

**Issue by jxhuliqun138** [shidenggui/easytrader#321]
## env

OS: win10
PYTHON_VERSION: 3.5
EASYTRADER_VERSION: 0.18.2
BROKER_TYPE: gj / ht / xq / xxx

## problem
执行user.prepare(user='xxx', password='xxx', comm_password='')，
银河客户端已经正常启动，账号密码自动输入并登陆进去后，报了以下错误

D:\Anaconda35\lib\site-packages\pywinauto\application.py:1064: UserWarning: 32-bit application should be automated using 32-bit Python (you use 64-bit Python)
  UserWarning)
Traceback (most recent call last):
  File "D:\Anaconda35\lib\site-packages\pywinauto\application.py", line 256, in __resolve_control
    criteria)
  File "D:\Anaconda35\lib\site-packages\pywinauto\timings.py", line 458, in wait_until_passes
    raise err
pywinauto.timings.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Anaconda35\lib\site-packages\easytrader\clienttrader.py", line 425, in prepare
    **kwargs
  File "D:\Anaconda35\lib\site-packages\easytrader\yh_clienttrader.py", line 82, in login
    self._switch_window_to_normal_mode()
  File "D:\Anaconda35\lib\site-packages\easytrader\yh_clienttrader.py", line 86, in _switch_window_to_normal_mode
    control_id=32812, class_name="Button"
  File "D:\Anaconda35\lib\site-packages\pywinauto\application.py", line 362, in __getattribute__
    ctrls = self.__resolve_control(self.criteria)
  File "D:\Anaconda35\lib\site-packages\pywinauto\application.py", line 259, in __resolve_control
    raise e.original_exception
  File "D:\Anaconda35\lib\site-packages\pywinauto\timings.py", line 436, in wait_until_passes
    func_val = func(*args, **kwargs)
  File "D:\Anaconda35\lib\site-packages\pywinauto\application.py", line 220, in __get_ctrl
    ctrl = self.backend.generic_wrapper_class(findwindows.find_element(**ctrl_criteria))
  File "D:\Anaconda35\lib\site-packages\pywinauto\findwindows.py", line 87, in find_element
    raise ElementNotFoundError(kwargs)
pywinauto.findwindows.ElementNotFoundError: {'top_level_only': False, 'parent': <win32_element_info.HwndElementInfo - '', Afx:400000:843:0:5:0, 133864>, 'control_id': 32812, 'backend': 'win32', 'class_name': 'Button'}

**Comment by jxhuliqun138** [comment]
@管理员，麻烦帮忙看一下

**Comment by cw3120** [comment]
我的也是相似的错误

**Comment by lwhuq** [comment]
出现同样问题，安装的是双子星金融终端-中国银河证券 8.50.40.01

**Comment by lwhuq** [comment]
配置
OS: win7
PYTHON_VERSION: 3.6.5
EASYTRADER_VERSION: 0.18.4
BROKER_TYPE: 双子星3.2，从issues里面的链接下的https://pan.baidu.com/s/1ByzfxcPRDtNEb6d8TQDTPw

步骤：
import easytrader

user = easytrader.use('yh_client')

user.prepare(user='xxxx', password='xxxxx')
C:\双子星-中国银河证券\xiadan.exe
C:\Users\qili\AppData\Local\Continuum\anaconda3\lib\site-packages\pywinauto\application.py:1064: UserWarning: 32-bit application should be automated using 32-bit Python (you use 64-bit Python)
  UserWarning)
file_path =  C:\Users\qili\AppData\Local\Temp\tmpy2ndnvrg
verify_code =  785
file_path =  C:\Users\qili\AppData\Local\Temp\tmp97ysgdh1
verify_code =  3235
file_path =  C:\Users\qili\AppData\Local\Temp\tmp0a1mr7qc
verify_code =  226)
file_path =  C:\Users\qili\AppData\Local\Temp\tmp9s1407m3
verify_code =  1%
file_path =  C:\Users\qili\AppData\Local\Temp\tmphe1zg7xi
verify_code =  07:2
file_path =  C:\Users\qili\AppData\Local\Temp\tmpym0q9vqm
verify_code =  822.6
C:\Users\qili\AppData\Local\Continuum\anaconda3\lib\site-packages\pywinauto\application.py:1064: UserWarning: 32-bit application should be automated using 32-bit Python (you use 64-bit Python)
  UserWarning)
Traceback (most recent call last):

  File "<ipython-input-3-9d19e8a910bd>", line 1, in <module>
    user.prepare(user='xxxx', password='xxxxx')

  File "C:\Users\qili\AppData\Local\Continuum\anaconda3\lib\site-packages\easytrader\clienttrader.py", line 425, in prepare
    **kwargs

  File "C:\Users\qili\AppData\Local\Continuum\anaconda3\lib\site-packages\easytrader\yh_clienttrader.py", line 81, in login
    self._switch_window_to_normal_mode()

  File "C:\Users\qili\AppData\Local\Continuum\anaconda3\lib\site-packages\easytrader\yh_clienttrader.py", line 85, in _switch_window_to_normal_mode
    control_id=32812, class_name="Button"

  File "C:\Users\qili\AppData\Local\Continuum\anaconda3\lib\site-packages\pywinauto\application.py", line 362, in __getattribute__
    ctrls = self.__resolve_control(self.criteria)

  File "C:\Users\qili\AppData\Local\Continuum\anaconda3\lib\site-packages\pywinauto\application.py", line 259, in __resolve_control
    raise e.original_exception

  File "C:\Users\qili\AppData\Local\Continuum\anaconda3\lib\site-packages\pywinauto\timings.py", line 436, in wait_until_passes
    func_val = func(*args, **kwargs)

  File "C:\Users\qili\AppData\Local\Continuum\anaconda3\lib\site-packages\pywinauto\application.py", line 220, in __get_ctrl
    ctrl = self.backend.generic_wrapper_class(findwindows.find_element(**ctrl_criteria))

  File "C:\Users\qili\AppData\Local\Continuum\anaconda3\lib\site-packages\pywinauto\findwindows.py", line 87, in find_element
    raise ElementNotFoundError(kwargs)

ElementNotFoundError: {'control_id': 32812, 'class_name': 'Button', 'top_level_only': False, 'parent': <win32_element_info.HwndElementInfo - '', #32770, 1251914>, 'backend': 'win32'}

**Comment by kn1f4** [comment]
同样遇到了相同的问题，建议适当加入web接口api

**Comment by Z0eDu** [comment]
请问有解决吗，这里也是相同问题，感谢！

**Comment by yourchanges** [comment]
同样的问题

**Comment by liuxuanqi** [comment]
同样的问题

**Comment by amangqq** [comment]
我用信达出现这种问题了，海通的没有

**Comment by oyjGit** [comment]
请问下百度网盘那个提取码是多少？
