### ISSUE TITLE
(1400, 'SetCursorPos', '无效的窗口句柄。')

### ISSUE THREAD

**Issue by yufeng0528** [shidenggui/easytrader#340]
## env

OS: win7
PYTHON_VERSION: 3.x
EASYTRADER_VERSION: 0.18.4
BROKER_TYPE: gj

## problem
```
Traceback (most recent call last):
  File "d:\python\lib\site-packages\celery\app\trace.py", line 385, in trace_task
    R = retval = fun(*args, **kwargs)
  File "d:\python\lib\site-packages\celery\app\trace.py", line 648, in __protected_call__
    return self.run(*args, **kwargs)
  File "D:\git\quantization-spider\task\trade_worker.py", line 73, in volume
    do_save_my_stocks()
  File "..\trade\capital.py", line 146, in do_save_my_stocks
    stocks = my_stocks()
  File "..\trade\capital.py", line 129, in my_stocks
    for item in trade_ops.position():
  File "..\trade\trade_ops.py", line 58, in position
    p = user.position
  File "d:\python\lib\site-packages\easytrader\clienttrader.py", line 112, in position
    return self._get_grid_data(self._config.COMMON_GRID_CONTROL_ID)
  File "d:\python\lib\site-packages\easytrader\clienttrader.py", line 333, in _get_grid_data
    return self.grid_strategy(self).get(control_id)
  File "d:\python\lib\site-packages\easytrader\grid_strategies.py", line 55, in get
    grid.type_keys("^A^C")
  File "d:\python\lib\site-packages\pywinauto\base_wrapper.py", line 943, in type_keys
    self.set_focus()
  File "d:\python\lib\site-packages\pywinauto\controls\hwndwrapper.py", line 1309, in set_focus
    mouse.move(coords=(-10000, 500))  # move the mouse out of screen to the left
  File "d:\python\lib\site-packages\pywinauto\mouse.py", line 244, in move
    _perform_click_input(button='move',coords=coords,button_down=False,button_up=False)
  File "d:\python\lib\site-packages\pywinauto\mouse.py", line 137, in _perform_click_input
    _set_cursor_pos((coords[0], coords[1]))
  File "d:\python\lib\site-packages\pywinauto\mouse.py", line 64, in _set_cursor_pos
    raise exc
  File "d:\python\lib\site-packages\pywinauto\mouse.py", line 59, in _set_cursor_pos
    win32api.SetCursorPos(coords)
pywintypes.error: (1400, 'SetCursorPos', '无效的窗口句柄。')
```
## how to repeat
用定时任务掉接口，会报这个错误，有碰到过吗？

**Comment by sanitizer84** [comment]
python目录\Scripts\下面有一个 pywinauto_postinstall.py，这个要手工在管理员权限的命令行执行一下，要向系统目录copy一些dll。然后试试看

**Comment by yufeng0528** [comment]
> python目录\Scripts\下面有一个 pywinauto_postinstall.py，这个要手工在管理员权限的命令行执行一下，要向系统目录copy一些dll。然后试试看

谢谢，我试试。
