### ISSUE TITLE
连接同花顺客户端报错

### ISSUE THREAD

**Issue by zhenghan3** [shidenggui/easytrader#358]
## env

OS: win10
PYTHON_VERSION: 3.7
EASYTRADER_VERSION: 0.xx.xx
BROKER_TYPE: gj / ht / xq / xxx

## problem
同花顺客户端版本8.80.60
已经登录登录交易系统并且放在后台
执行user = easytrader.use('ths')这一句就会报错

报错提示如下：

D:\IDE\Miniconda\main\envs\stocks\python.exe "D:/Personal/Dropbox (个人)/Projects/Python/Stocks/Stock_autotrader.py"
Traceback (most recent call last):
  File "D:\IDE\Miniconda\main\envs\stocks\lib\ctypes\__init__.py", line 121, in WINFUNCTYPE
    return _win_functype_cache[(restype, argtypes, flags)]
KeyError: (<class 'ctypes.HRESULT'>, (<class 'ctypes.c_long'>, <class 'comtypes.automation.tagVARIANT'>, <class 'comtypes.LP_POINTER(IUIAutomationCondition)'>), 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:/Personal/Dropbox (个人)/Projects/Python/Stocks/Stock_autotrader.py", line 3, in <module>
    user = easytrader.use('ths')
  File "D:\IDE\Miniconda\main\envs\stocks\lib\site-packages\easytrader\api.py", line 57, in use
    from .clienttrader import ClientTrader
  File "D:\IDE\Miniconda\main\envs\stocks\lib\site-packages\easytrader\clienttrader.py", line 12, in <module>
    from pywinauto import findwindows, timings
  File "D:\IDE\Miniconda\main\envs\stocks\lib\site-packages\pywinauto\__init__.py", line 89, in <module>
    from . import findwindows
  File "D:\IDE\Miniconda\main\envs\stocks\lib\site-packages\pywinauto\findwindows.py", line 42, in <module>
    from . import controls
  File "D:\IDE\Miniconda\main\envs\stocks\lib\site-packages\pywinauto\controls\__init__.py", line 36, in <module>
    from . import uiawrapper # register "uia" back-end (at the end of uiawrapper module)
  File "D:\IDE\Miniconda\main\envs\stocks\lib\site-packages\pywinauto\controls\uiawrapper.py", line 47, in <module>
    from ..uia_defines import IUIA
  File "D:\IDE\Miniconda\main\envs\stocks\lib\site-packages\pywinauto\uia_defines.py", line 181, in <module>
    pattern_ids = _build_pattern_ids_dic()
  File "D:\IDE\Miniconda\main\envs\stocks\lib\site-packages\pywinauto\uia_defines.py", line 169, in _build_pattern_ids_dic
    if hasattr(IUIA().ui_automation_client, cls_name):
  File "D:\IDE\Miniconda\main\envs\stocks\lib\site-packages\pywinauto\uia_defines.py", line 50, in __call__
    cls._instances[cls] = super(_Singleton, cls).__call__(*args, **kwargs)
  File "D:\IDE\Miniconda\main\envs\stocks\lib\site-packages\pywinauto\uia_defines.py", line 60, in __init__
    self.UIA_dll = comtypes.client.GetModule('UIAutomationCore.dll')
  File "D:\IDE\Miniconda\main\envs\stocks\lib\site-packages\comtypes\client\_generate.py", line 110, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "D:\IDE\Miniconda\main\envs\stocks\lib\site-packages\comtypes\client\_generate.py", line 184, in _CreateWrapper
    mod = _my_import(fullname)
  File "D:\IDE\Miniconda\main\envs\stocks\lib\site-packages\comtypes\client\_generate.py", line 24, in _my_import
    return __import__(fullname, globals(), locals(), ['DUMMY'])
  File "D:\IDE\Miniconda\main\envs\stocks\lib\site-packages\comtypes\gen\_944DE083_8FB8_45CF_BCB7_C477ACB2F897_0_1_0.py", line 331, in <module>
    ( ['out', 'retval'], POINTER(POINTER(IUIAutomationElement)), 'element' )),
  File "D:\IDE\Miniconda\main\envs\stocks\lib\site-packages\comtypes\__init__.py", line 329, in __setattr__
    self._make_methods(value)
  File "D:\IDE\Miniconda\main\envs\stocks\lib\site-packages\comtypes\__init__.py", line 698, in _make_methods
    prototype = WINFUNCTYPE(restype, *argtypes)
  File "D:\IDE\Miniconda\main\envs\stocks\lib\ctypes\__init__.py", line 123, in WINFUNCTYPE
    class WinFunctionType(_CFuncPtr):
TypeError: item 2 in _argtypes_ passes a union by value, which is unsupported.

Process finished with exit code 1

**Comment by fzdyzgly** [comment]
请问怎么解决的？？
