### ISSUE TITLE
连接通用同花顺客户端失败

### ISSUE THREAD

**Issue by fzdyzgly** [shidenggui/easytrader#359]
## env

OS: win10
PYTHON_VERSION: 3.7
EASYTRADER_VERSION: 0.18.4
BROKER_TYPE: gj / ht / xq / xxx

## problem
Traceback (most recent call last):
  File "C:\Users\51413\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 121, in WINFUNCTYPE
    return _win_functype_cache[(restype, argtypes, flags)]
KeyError: (<class 'ctypes.HRESULT'>, (<class 'ctypes.c_long'>, <class 'comtypes.automation.tagVARIANT'>, <class 'comtypes.LP_POINTER(IUIAutomationCondition)'>), 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:/Pytrade/MT191217/MT/strateTrade.py", line 53, in <module>
    user = easytrader.use('ths')
  File "C:\Pytrade\MT191217\MT\venv\lib\site-packages\easytrader\api.py", line 46, in use
    from .clienttrader import ClientTrader
  File "C:\Pytrade\MT191217\MT\venv\lib\site-packages\easytrader\clienttrader.py", line 11, in <module>
    from . import grid_strategies, helpers, pop_dialog_handler
  File "C:\Pytrade\MT191217\MT\venv\lib\site-packages\easytrader\grid_strategies.py", line 8, in <module>
    import pywinauto.clipboard
  File "C:\Pytrade\MT191217\MT\venv\lib\site-packages\pywinauto\__init__.py", line 89, in <module>
    from . import findwindows
  File "C:\Pytrade\MT191217\MT\venv\lib\site-packages\pywinauto\findwindows.py", line 42, in <module>
    from . import controls
  File "C:\Pytrade\MT191217\MT\venv\lib\site-packages\pywinauto\controls\__init__.py", line 36, in <module>
    from . import uiawrapper # register "uia" back-end (at the end of uiawrapper module)
  File "C:\Pytrade\MT191217\MT\venv\lib\site-packages\pywinauto\controls\uiawrapper.py", line 47, in <module>
    from ..uia_defines import IUIA
  File "C:\Pytrade\MT191217\MT\venv\lib\site-packages\pywinauto\uia_defines.py", line 181, in <module>
    pattern_ids = _build_pattern_ids_dic()
  File "C:\Pytrade\MT191217\MT\venv\lib\site-packages\pywinauto\uia_defines.py", line 169, in _build_pattern_ids_dic
    if hasattr(IUIA().ui_automation_client, cls_name):
  File "C:\Pytrade\MT191217\MT\venv\lib\site-packages\pywinauto\uia_defines.py", line 50, in __call__
    cls._instances[cls] = super(_Singleton, cls).__call__(*args, **kwargs)
  File "C:\Pytrade\MT191217\MT\venv\lib\site-packages\pywinauto\uia_defines.py", line 60, in __init__
    self.UIA_dll = comtypes.client.GetModule('UIAutomationCore.dll')
  File "C:\Pytrade\MT191217\MT\venv\lib\site-packages\comtypes\client\_generate.py", line 110, in GetModule
    mod = _CreateWrapper(tlib, pathname)
  File "C:\Pytrade\MT191217\MT\venv\lib\site-packages\comtypes\client\_generate.py", line 184, in _CreateWrapper
    mod = _my_import(fullname)
  File "C:\Pytrade\MT191217\MT\venv\lib\site-packages\comtypes\client\_generate.py", line 24, in _my_import
    return __import__(fullname, globals(), locals(), ['DUMMY'])
  File "C:\Pytrade\MT191217\MT\venv\lib\site-packages\comtypes\gen\_944DE083_8FB8_45CF_BCB7_C477ACB2F897_0_1_0.py", line 282, in <module>
    ( ['out', 'retval'], POINTER(POINTER(IUIAutomationElement)), 'element' )),
  File "C:\Pytrade\MT191217\MT\venv\lib\site-packages\comtypes\__init__.py", line 329, in __setattr__
    self._make_methods(value)
  File "C:\Pytrade\MT191217\MT\venv\lib\site-packages\comtypes\__init__.py", line 698, in _make_methods
    prototype = WINFUNCTYPE(restype, *argtypes)
  File "C:\Users\51413\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 123, in WINFUNCTYPE
    class WinFunctionType(_CFuncPtr):
TypeError: item 2 in _argtypes_ passes a union by value, which is unsupported.
## how to repeat

执行user = easytrader.use('ths')报错
之前测试没问题，今天换了台电脑，更新了一下版本，不知道为什么连不上了，求助，多谢~！

**Comment by fzdyzgly** [comment]
已经找到原因  是由于python 3.7.4以下版本暂不支持 pywinauto 降python版本即可

**Comment by GuancongLuo** [comment]
3.6.12 和 3.7.9 版本均出现

```
Traceback (most recent call last):
  File "1_get_account_info.py", line 3, in <module>
    user = easytrader.use('ths')
  File "C:\Users\Clarance\anaconda3\envs\easytrader\lib\site-packages\easytrader\api.py", line 62, in use
    from .clienttrader import ClientTrader
  File "C:\Users\Clarance\anaconda3\envs\easytrader\lib\site-packages\easytrader\clienttrader.py", line 12, in <module>
    from pywinauto import findwindows, timings
  File "C:\Users\Clarance\anaconda3\envs\easytrader\lib\site-packages\pywinauto\__init__.py", 
line 59, in <module>
    import win32api  # noqa: E402
ModuleNotFoundError: No module named 'win32api'
```

请问该如何解决？感谢
