### ISSUE TITLE
连续两次执行balance，后面那次出错

### ISSUE THREAD

**Issue by flyingfish6084** [shidenggui/easytrader#360]
## env

OS: win10
PYTHON_VERSION: 3.7
EASYTRADER_VERSION: newest
BROKER_TYPE: ht

## problem
user.balance
2020-02-20 18:11:01,508 [DEBUG] perf.py 39: '_switch_left_menus' consume 0.3429 sec, cpu 0.0156 sec. args (['查询[F4]', '资金股票'],), extra args {}
Out[3]: 
{'资金余额': 197101.89,
 '冻结资金': 0.0,
 '可用金额': 197101.89,
 '可取金额': 197101.89,
 '股票市值': 0.0,
 '总资产': 197101.89}

user.balance
2020-02-20 18:11:08,213 [DEBUG] perf.py 39: '_switch_left_menus' consume 0.3435 sec, cpu 0.0000 sec. args (['查询[F4]', '资金股票'],), extra args {}
Traceback (most recent call last):

  File "<ipython-input-4-1fb411890304>", line 1, in <module>
    user.balance

  File "C:\Users\abc\Anaconda3\lib\site-packages\easytrader\ht_clienttrader.py", line 66, in balance
    return self._get_balance_from_statics()

  File "C:\Users\abc\Anaconda3\lib\site-packages\easytrader\ht_clienttrader.py", line 73, in _get_balance_from_statics
    control_id=control_id, class_name="Static"

  File "C:\Users\abc\Anaconda3\lib\site-packages\pywinauto\application.py", line 379, in __getattribute__
    ctrls = self.__resolve_control(self.criteria)

  File "C:\Users\abc\Anaconda3\lib\site-packages\pywinauto\application.py", line 261, in __resolve_control
    raise e.original_exception

  File "C:\Users\abc\Anaconda3\lib\site-packages\pywinauto\timings.py", line 436, in wait_until_passes
    func_val = func(*args, **kwargs)

  File "C:\Users\abc\Anaconda3\lib\site-packages\pywinauto\application.py", line 222, in __get_ctrl
    ctrl = self.backend.generic_wrapper_class(findwindows.find_element(**ctrl_criteria))

  File "C:\Users\abc\Anaconda3\lib\site-packages\pywinauto\findwindows.py", line 87, in find_element
    raise ElementNotFoundError(kwargs)

ElementNotFoundError: {'control_id': 1012, 'class_name': 'Static', 'top_level_only': False, 'parent': <win32_element_info.HwndElementInfo - '网上股票交易系统5.0', AfxFrameOrView42s, 397316>, 'backend': 'win32'}
## how to repeat
观察到一个现象不知道跟问题有没有关系。第一次执行balance成功以后看了一下华泰客户端界面，左侧栏里选定了股转系统->解除邀约

**Comment by flyingfish6084** [comment]
参考了前面已经关闭的问题单，问题貌似是因为click()在我的windows版本上不好使。把click()修改为select()问题解决。

**Comment by njtuzk** [comment]
修改为select()问题解决

**Comment by qmzhn** [comment]
> 参考了前面已经关闭的问题单，问题貌似是因为click()在我的windows版本上不好使。把click()修改为select()问题解决。
兄弟，我很欣赏你！

**Comment by flyingfish6084** [comment]
@qmzhn ：）多多交流哈！

**Comment by QuantumLiu** [comment]
请问是改哪里？哪个关闭的issues？
