### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by distone** [shidenggui/easytrader#37]
On running

>>> import easytrader
>>> easytrader.use('yjb')

pop up this error message: 

Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    easytrader.use('yjb')
  File "C:\python35\Lib\site-packages\easytrader\api.py", line 27, in use
    return YJBTrader()
  File "C:\python35\Lib\site-packages\easytrader\yjbtrader.py", line 24, in __init__
    super(YJBTrader, self).__init__()
  File "C:\python35\Lib\site-packages\easytrader\webtrader.py", line 31, in __init__
    self.__read_config()
  File "C:\python35\Lib\site-packages\easytrader\webtrader.py", line 99, in __read_config
    self.global_config = helpers.file2dict(self.global_config_path)
  File "C:\python35\Lib\site-packages\easytrader\helpers.py", line 42, in file2dict
    return json.load(f)
  File "C:\python35\Lib\json\__init__.py", line 265, in load
    return loads(fp.read(),
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 190: illegal multibyte sequence

I run sys.getdefaultencoding(), it returns 'utf-8'. 
How to fix this error? 

Thanks!

**Comment by shidenggui** [comment]
fix by https://github.com/shidenggui/easytrader/commit/22ea633ca01a940d85837016fd45a0f25a32d109
