### ISSUE TITLE
华泰普通股票账户可用，但是信用(融资融券)账户不能使用，可否增加华泰信用的账户的操作

### ISSUE THREAD

**Issue by lsps2009** [shidenggui/easytrader#391]
## env

OS: win7/ win10 / mac / linux
PYTHON_VERSION: 3.x
EASYTRADER_VERSION: 0.xx.xx
BROKER_TYPE: gj / ht / xq / xxx

## problem
2020-07-11 16:03:22,800 [ERROR] clienttrader.py 471: error occurred when trying to get left menus
Traceback (most recent call last):
  File "C:\Users\LS\AppData\Local\Programs\Python\Python36\lib\site-packages\easytrader\clienttrader.py", line 467, in _get_left_menus_handle
    handle.wait("ready", 2)
  File "C:\Users\LS\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinauto\application.py", line 512, in wait
    lambda: self.__check_all_conditions(check_method_names, retry_interval))
  File "C:\Users\LS\AppData\Local\Programs\Python\Python36\lib\site-packages\pywinauto\timings.py", line 375, in wait_until
    raise err
pywinauto.timings.TimeoutError: timed out

**Comment by twostonescy** [comment]
mark
