### ISSUE TITLE
easytrader不支持mac吗，看中文文档说支持

### ISSUE THREAD

**Issue by dillonchen001** [shidenggui/easytrader#396]
## env

OS:  mac
PYTHON_VERSION: 3.x
EASYTRADER_VERSION: 0.xx.xx
BROKER_TYPE: ths

## how to repeat

Traceback (most recent call last):
  File "jy.py", line 23, in <module>
    main()
  File "jy.py", line 6, in main
    user = easytrader.use('ths')
  File "/usr/local/lib/python3.7/site-packages/easytrader/api.py", line 62, in use
    from .clienttrader import ClientTrader
  File "/usr/local/lib/python3.7/site-packages/easytrader/clienttrader.py", line 12, in <module>
    from pywinauto import findwindows, timings
  File "/usr/local/lib/python3.7/site-packages/pywinauto/findwindows.py", line 39, in <module>
    from . import win32functions
  File "/usr/local/lib/python3.7/site-packages/pywinauto/win32functions.py", line 35, in <module>
    from ctypes import wintypes
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/wintypes.py", line 20, in <module>
    class VARIANT_BOOL(ctypes._SimpleCData):
ValueError: _type_ 'v' not supported

**Comment by shidenggui** [comment]
不支持
