### ISSUE TITLE
跟踪雪球组合失败

### ISSUE THREAD

**Issue by dillonchen001** [shidenggui/easytrader#410]
## env

OS: win7
PYTHON_VERSION: 3.x
EASYTRADER_VERSION: 0.xx.xx
BROKER_TYPE: ths

## problem
跟踪雪球组合的获取组合名称失败，返回http 400
2020-11-07 20:14:42,839 [INFO] xq_follower.py 47: 登录成功
2020-11-07 20:14:42,886 [INFO] xq_follower.py 142: 获取策略名: <Response [400]>
<Response [400]>
2020-11-07 20:14:42,886 [ERROR] xq_follower.py 113: 抽取交易id和策略名失败, 无效
模拟交易url: ZH2099343
Traceback (most recent call last):
  File "cli_sg.py", line 15, in <module>
    main()
  File "cli_sg.py", line 12, in main
    xq_follower.follow(xq_user, 'ZH2099343', total_assets=30000, slippage=0.01,
track_interval=3)
  File "C:\Program Files\Python36\lib\site-packages\easytrader\xq_follower.py",
line 111, in follow
    strategy_name = self.extract_strategy_name(strategy_url)
  File "C:\Program Files\Python36\lib\site-packages\easytrader\xq_follower.py",
line 145, in extract_strategy_name
    return rep.json()[info_index]["name"]
KeyError: 0

**Comment by dillonchen001** [comment]
2020-11-07 20:14:42,839 [INFO] xq_follower.py 47: 登录成功
2020-11-07 20:14:42,886 [INFO] xq_follower.py 142: 获取策略名: <Response [400]>
<Response [400]>
2020-11-07 20:14:42,886 [ERROR] xq_follower.py 113: 抽取交易id和策略名失败, 无效
模拟交易url: ZH2099343
Traceback (most recent call last):
  File "cli_sg.py", line 15, in <module>
    main()
  File "cli_sg.py", line 12, in main
    xq_follower.follow(xq_user, 'ZH2099343', total_assets=30000, slippage=0.01,
track_interval=3)
  File "C:\Program Files\Python36\lib\site-packages\easytrader\xq_follower.py",
line 111, in follow
    strategy_name = self.extract_strategy_name(strategy_url)
  File "C:\Program Files\Python36\lib\site-packages\easytrader\xq_follower.py",
line 145, in extract_strategy_name
    return rep.json()[info_index]["name"]
KeyError: 0
