### ISSUE TITLE
银河证券 yh_client 登入后，总是反复报错，但程序继续运行

### ISSUE THREAD

**Issue by TrW236** [shidenggui/easytrader#417]
## env

OS:  win10 
PYTHON_VERSION: 3.6
EASYTRADER_VERSION: 应该是最新版
BROKER_TYPE: yh_client

## problem
登入银河证券软件之后，总是反复出现以下报错，但程序继续运行
```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "C:\Users\Tianran\Anaconda3\envs\auto_trade\lib\site-packages\pywinauto\win32_element_info.py", line 138, in enum_window_proc
    if title is not None and title != element.rich_text:
  File "C:\Users\Tianran\Anaconda3\envs\auto_trade\lib\site-packages\pywinauto\win32_element_info.py", line 83, in rich_text
    return handleprops.text(self.handle)
  File "C:\Users\Tianran\Anaconda3\envs\auto_trade\lib\site-packages\pywinauto\handleprops.py", line 88, in text
    buffer_ = ctypes.create_unicode_buffer(length)
  File "C:\Users\Tianran\Anaconda3\envs\auto_trade\lib\ctypes\__init__.py", line 288, in create_unicode_buffer
    buftype = c_wchar * init
OverflowError: cannot fit 'int' into an index-sized integer
```

**Comment by Frank-FanQMeng** [comment]
你好，我登录华泰证券客户端也出现类似的情况，请问你的问题解决了吗？
