### ISSUE TITLE
请问支持苹果的M1芯片通过PD安装的ARM版Win10吗？

### ISSUE THREAD

**Issue by auspix** [shidenggui/easytrader#420]
## env

OS: win7/ win10 / mac / linux
PYTHON_VERSION: 3.x
EASYTRADER_VERSION: 0.xx.xx
BROKER_TYPE: gj / ht / xq / xxx

**Comment by auspix** [comment]
M1芯片上通过PD安装Win10 ARM

c:\git\easytrader>py test_myht.py
Traceback (most recent call last):
  File "test_myht.py", line 11, in <module>
    user = easytrader.use("ht_client",True)
  File "c:\git\easytrader\easytrader\api.py", line 42, in use
    from .ht_clienttrader import HTClientTrader
  File "c:\git\easytrader\easytrader\ht_clienttrader.py", line 6, in <module>
    from easytrader import grid_strategies
  File "c:\git\easytrader\easytrader\grid_strategies.py", line 15, in <module>
    from easytrader.utils.win_gui import SetForegroundWindow, ShowWindow, win32defines
  File "c:\git\easytrader\easytrader\utils\win_gui.py", line 3, in <module>
    from pywinauto.win32functions import SetForegroundWindow, ShowWindow
ImportError: cannot import name 'SetForegroundWindow' from 'pywinauto.win32functions' (C:\Apps\Python\Python38\lib\site-packages\pywinauto\win32functions.py)

**Comment by shidenggui** [comment]
没有测试过，不太清楚。

**Comment by auspix** [comment]
谢谢，部署到腾讯云上了，很流畅。
