### ISSUE TITLE
雪球跟踪组合出现不支持市场类型的错误

### ISSUE THREAD

**Issue by nwpujohneewang** [shidenggui/easytrader#451]
## env

OS:  win10 
PYTHON_VERSION: 3.8
EASYTRADER_VERSION: 0.xx.xx
BROKER_TYPE: ths

## problem
跟踪组合的时候，ths下单会失败，提示的错误是不支持对应的市场类型
## how to repeat
2021-09-27 14:23:59,159 [INFO] follower.py 202: 策略 [Test] 发送指令到交易队列, 股票: sz002807 动作: buy 数量: 100 价格: 3.84 信号产生时间: 2021-09-27 14:23:49
Exception in thread Thread-1:
Traceback (most recent call last):
  File "E:\Program\conda\envs\python32\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "E:\Program\conda\envs\python32\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Program\conda\envs\python32\lib\site-packages\easytrader\follower.py", line 353, in trade_worker
    self._execute_trade_cmd(
  File "E:\Program\conda\envs\python32\lib\site-packages\easytrader\follower.py", line 318, in _execute_trade_cmd
    response = getattr(user, trade_cmd["action"])(**args)
  File "E:\Program\conda\envs\python32\lib\site-packages\easytrader\utils\perf.py", line 18, in wrapper
    return f(*args, **kwargs)
  File "E:\Program\conda\envs\python32\lib\site-packages\easytrader\clienttrader.py", line 217, in buy
    return self.trade(security, price, amount)
  File "E:\Program\conda\envs\python32\lib\site-packages\easytrader\clienttrader.py", line 415, in trade
    self._set_trade_params(security, price, amount)
  File "E:\Program\conda\envs\python32\lib\site-packages\easytrader\clienttrader.py", line 459, in _set_trade_params
    self._set_stock_exchange_type("深圳Ａ股")
  File "E:\Program\conda\envs\python32\lib\site-packages\easytrader\clienttrader.py", line 321, in _set_stock_exchange_type
    raise TypeError("不支持对应的市场类型: {}".format(ttype))
TypeError: 不支持对应的市场类型: 深圳Ａ股

**Comment by lovelykd** [comment]
@nwpujohneewang 
![image](https://user-images.githubusercontent.com/2628956/142598717-782ea96a-d820-4c53-a54e-888a0cc9196e.png)
我下载了最新版的华泰证券客户端 - 网上交易系统（专业版Ⅲ）V6.08，发现市场类型的选项是深圳Ａ和上海Ａ，没有`股`字
你可以看一下你的客户端的情况

**Comment by nwpujohneewang** [comment]
感谢感谢，我找到了报错的那段代码，应该是在买入卖出的时候会选择是上海还是深圳，然后我直接把这步操作注释掉了就好了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shidenggui/easytrader"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月19日(星期五) 下午5:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shidenggui/easytrader] 雪球跟踪组合出现不支持市场类型的错误 (#451)





 
@nwpujohneewang
 
 我下载了最新版的华泰证券客户端 - 网上交易系统（专业版Ⅲ）V6.08，发现市场类型的选项是深圳Ａ和上海Ａ，没有股字
 你可以看一下你的客户端的情况
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
