### ISSUE TITLE
求解决：我的同花顺版本用是V8.90.91,多次调用持仓等数据时，就会弹出要输入验证码，但是程序中并没有识别出验证码，导致生成xls失败，获取对应的持仓数据也失败了

### ISSUE THREAD

**Issue by tequilawu** [shidenggui/easytrader#459]
## env

OS: win7/ win10 / mac / linux
PYTHON_VERSION: 3.x
EASYTRADER_VERSION: 0.xx.xx
BROKER_TYPE: gj / ht / xq / xxx

## problem
![image](https://user-images.githubusercontent.com/21970305/153231857-a398bbfb-6b44-44c6-b409-b85bc50be13f.png)

报错信息如下：
Traceback (most recent call last):
  File "c:/Users/admin/Desktop/demo01.py", line 21, in <module>
    position = user.position
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\easytrader\clienttrader.py", line 148, in position
    return self._get_grid_data(self._config.COMMON_GRID_CONTROL_ID)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\easytrader\clienttrader.py", line 490, in _get_grid_data
    return self.grid_strategy_instance.get(control_id)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\easytrader\grid_strategies.py", line 204, in get    return self._format_grid_data(temp_path)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\site-packages\easytrader\grid_strategies.py", line 207, in _format_grid_data
    with open(data, encoding="gbk", errors="replace") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\tmpnah5cm4i.xls'

求大神解答下

**Comment by shmily825** [comment]
我也是，求解决
