### ISSUE TITLE
各位大佬，不支持对应市场类型，无法下单是啥情况

### ISSUE THREAD

**Issue by sqr1sqr** [shidenggui/easytrader#480]
## env

OS: win7/ win10 / mac / linux
PYTHON_VERSION: 3.x
EASYTRADER_VERSION: 0.xx.xx
BROKER_TYPE: gj / ht / xq / xxx

## 
Exception in thread Thread-1:
Traceback (most recent call last):
  File "D:\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "D:\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Python38\lib\site-packages\easytrader\follower.py", line 353, in trade_worker
    self._execute_trade_cmd(
  File "D:\Python38\lib\site-packages\easytrader\follower.py", line 318, in _execute_trade_cmd
    response = getattr(user, trade_cmd["action"])(**args)
  File "D:\Python38\lib\site-packages\easytrader\utils\perf.py", line 18, in wrapper
    return f(*args, **kwargs)
  File "D:\Python38\lib\site-packages\easytrader\clienttrader.py", line 223, in sell
    return self.trade(security, price, amount)
  File "D:\Python38\lib\site-packages\easytrader\clienttrader.py", line 415, in trade
    self._set_trade_params(security, price, amount)
  File "D:\Python38\lib\site-packages\easytrader\clienttrader.py", line 461, in _set_trade_params
    self._set_stock_exchange_type("上海Ａ股")
  File "D:\Python38\lib\site-packages\easytrader\clienttrader.py", line 321, in _set_stock_exchange_type
    raise TypeError("不支持对应的市场类型: {}".format(ttype))
TypeError: 不支持对应的市场类型: 上海Ａ股

**Comment by bihaiyouyou** [comment]
源码失修多时，您可复制一下您对源码的修改，或能帮您解决。或者，看这里直接用成品exe软件：https://www.dreamhyqi.com/
