### ISSUE TITLE
使用雪球模拟交易，查询资金或持仓时提示错误

### ISSUE THREAD

**Issue by yoyobbs** [shidenggui/easytrader#81]
百度了无数次解决无果，期待作者您能知道是什么问题？
我咨询了群内一些成功的朋友，他们都可以正常查询，而我在win与ubuntu下均提示这个错误。

[2016-07-14 16:30:29.654315] DEBUG: xqtrader.py: login status: SUCCESS
Traceback (most recent call last):
  File "F:\Program Files\JetBrains\PyCharm 5.0.3\helpers\pycharm\utrunner.py", line 129, in <module>
    module = loadSource(a[0])
  File "F:\Program Files\JetBrains\PyCharm 5.0.3\helpers\pycharm\utrunner.py", line 41, in loadSource
    module = imp.load_source(moduleName, fileName)
  File "E:\Python35\lib\imp.py", line 172, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "F:\py\easytrader\test.py", line 9, in <module>
    user.balance
  File "F:\py\easytrader\easytrader\webtrader.py", line 113, in balance
    return self.get_balance()
  File "F:\py\easytrader\easytrader\xqtrader.py", line 161, in get_balance
    portfolio_info = self.__get_portfolio_info(portfolio_code)  # 组合信息
  File "F:\py\easytrader\easytrader\xqtrader.py", line 148, in __get_portfolio_info
    html = self.__get_html(url)
  File "F:\py\easytrader\easytrader\xqtrader.py", line 114, in __get_html
    resp = urllib.request.urlopen(req)
  File "E:\Python35\lib\urllib\request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "E:\Python35\lib\urllib\request.py", line 465, in open
    response = self._open(req, data)
  File "E:\Python35\lib\urllib\request.py", line 483, in _open
    '_open', req)
  File "E:\Python35\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "E:\Python35\lib\urllib\request.py", line 1283, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "E:\Python35\lib\urllib\request.py", line 1240, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "E:\Python35\lib\http\client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "E:\Python35\lib\http\client.py", line 1118, in _send_request
    self.putrequest(method, url, **skips)
  File "E:\Python35\lib\http\client.py", line 960, in putrequest
    self._output(request.encode('ascii'))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 7-12: ordinal not in range(128)

**Comment by yoyobbs** [comment]
贴上运行代码

# -*- coding: utf-8 -*-
import easytrader
user = easytrader.use('xq')
user.prepare('xq.json')
user.balance

**Comment by shidenggui** [comment]
可能你的终端无法显示中文，你试着在 tmux 里面运行脚本试下

**Comment by yoyobbs** [comment]
我使用win10的cmd界面操作，按理是可以中文。今晚我回去在ubuntu试试tmux的操作再上来回复

**Comment by yoyobbs** [comment]
昨晚使用了ubuntu中的tmux操作，还是会出现'ascii' codec can't encode characters in position 7-12: ordinal not in range(128)的错误，实在是难以理解

**Comment by yoyobbs** [comment]
作者您好，问题原因我已经找到了。
xq.json中，"portfolio_code": "组合信息"，这段话我无修改导致的
