### ISSUE TITLE
银河check_available_cancels()

### ISSUE THREAD

**Issue by fayeshine** [shidenggui/easytrader#93]
```
user.check_available_cancels()
Traceback (most recent call last):

  File "<ipython-input-52-d6a9f31533d3>", line 1, in <module>
    user.check_available_cancels()

  File "/home/wenjian/anaconda3/lib/python3.5/site-packages/easytrader-0.7.2-py3.5.egg/easytrader/yhtrader.py", line 150, in check_available_cancels
    ,   "canceled_vol": int(item[9])

ValueError: invalid literal for int() with base 10: 'A**********'
```
A*********为A股账号，我隐去了

**Comment by fayeshine** [comment]
股东代码可能为A*****,无法转为int，话说也必要转把

**Comment by fayeshine** [comment]
这个cancel_list和实际的根本对应不上。。。。， canceld_vol怎么对应股东代码取了

**Comment by shidenggui** [comment]
银河有些部分用了正则，只测试了2,3个账户，对某些情况还没有适配，可能需要自己修改
