### ISSUE TITLE
今天更新到最新版，然后不断弹出下面的东西！

### ISSUE THREAD

**Issue by lyghid** [shidenggui/easytrader#96]
--- Logging error ---
Traceback (most recent call last):
  File "D:\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "D:\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 393, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "D:\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 389, in _make_request
    httplib_response = conn.getresponse()
  File "D:\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\http\client.py", line 1227, in getresponse
    response.begin()
  File "D:\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\http\client.py", line 386, in begin
    version, status, reason = self._read_status()
  File "D:\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\http\client.py", line 348, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "D:\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\socket.py", line 378, in readinto
    return self._sock.recv_into(b)
  File "D:\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\ssl.py", line 748, in recv_into
    return self.read(nbytes, buffer)
  File "D:\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\ssl.py", line 620, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\site-packages\requests\adapters.py", line 417, in send
    timeout=timeout
  File "D:\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 640, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "D:\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\site-packages\requests\packages\urllib3\util\retry.py", line 261, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "D:\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\site-packages\requests\packages\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "D:\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 595, in urlopen
    chunked=chunked)
  File "D:\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 393, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "D:\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\site-packages\requests\packages\urllib3\connectionpool.py", line 389, in _make_request
    httplib_response = conn.getresponse()
  File "D:\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\http\client.py", line 1227, in getresponse
    response.begin()
  File "D:\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\http\client.py", line 386, in begin
    version, status, reason = self._read_status()
  File "D:\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\http\client.py", line 348, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "D:\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\socket.py", line 378, in readinto
    return self._sock.recv_into(b)
  File "D:\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\ssl.py", line 748, in recv_into
    return self.read(nbytes, buffer)
  File "D:\WinPython-64bit-3.4.4.2\python-3.4.4.amd64\lib\ssl.py", line 620, in read
    v = self._sslobj.read(len, buffer)
requests.packages.urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

**Comment by shidenggui** [comment]
需要跟具体的日志信息
